import {
  mysqlTable,
  varchar,
  text,
  int,
  float,
  timestamp,
} from "drizzle-orm/mysql-core";

export const routes = mysqlTable("routes", {
  id: int("id").autoincrement().primaryKey(),
  routeId: varchar("route_id", { length: 20 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  nameShort: varchar("name_short", { length: 100 }),
  region: varchar("region", { length: 50 }).notNull(),
  type: varchar("type", { length: 50 }).notNull(),
  durationDays: int("duration_days").notNull(),
  budgetPerDay: int("budget_per_day").notNull(),
  difficulty: int("difficulty").notNull(),
  rating: float("rating").notNull().default(0),
  season: varchar("season", { length: 50 }).notNull(),
  transport: varchar("transport", { length: 50 }).notNull(),
  groupType: varchar("group_type", { length: 50 }).notNull(),
  description: text("description"),
  longDescription: text("long_description"),
  natureScore: int("nature_score").notNull().default(1),
  cultureScore: int("culture_score").notNull().default(1),
  comfortScore: int("comfort_score").notNull().default(1),
  adventureScore: int("adventure_score").notNull().default(1),
  costScore: int("cost_score").notNull().default(1),
  profileMatch: varchar("profile_match", { length: 50 }),
  imageUrl: varchar("image_url", { length: 255 }),
  objectIds: text("object_ids"),
  startLat: float("start_lat"),
  startLng: float("start_lng"),
  pathCoords: text("path_coords"),
  dayMarkers: text("day_markers"),
  featured: int("featured").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const objects = mysqlTable("objects", {
  id: int("id").autoincrement().primaryKey(),
  objectId: varchar("object_id", { length: 20 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  category: varchar("category", { length: 50 }).notNull(),
  region: varchar("region", { length: 50 }).notNull(),
  description: text("description"),
  price: int("price").notNull().default(0),
  currency: varchar("currency", { length: 10 }).default("сом"),
  lat: float("lat").notNull(),
  lng: float("lng").notNull(),
  imageUrl: varchar("image_url", { length: 255 }),
  tags: text("tags"),
  season: varchar("season", { length: 50 }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const guesthouses = mysqlTable("guesthouses", {
  id: int("id").autoincrement().primaryKey(),
  ghId: varchar("gh_id", { length: 20 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  city: varchar("city", { length: 100 }).notNull(),
  region: varchar("region", { length: 50 }).notNull(),
  type: varchar("type", { length: 50 }).notNull(),
  typeColor: varchar("type_color", { length: 20 }),
  description: text("description"),
  pricePerNight: int("price_per_night").notNull().default(0),
  season: varchar("season", { length: 50 }),
  rating: float("rating").default(0),
  kgstdScore: int("kgstd_score").default(0),
  kgstdMax: int("kgstd_max").default(54),
  kgstdPct: float("kgstd_pct").default(0),
  kgstdStars: int("kgstd_stars").default(0),
  kgstdAnswers: text("kgstd_answers"),
  facilities: text("facilities"),
  lat: float("lat"),
  lng: float("lng"),
  imageUrl: varchar("image_url", { length: 255 }),
  phone: varchar("phone", { length: 50 }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const kgstdCriteria = mysqlTable("kgstd_criteria", {
  id: int("id").autoincrement().primaryKey(),
  criterionId: varchar("criterion_id", { length: 20 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  aspect: varchar("aspect", { length: 50 }).notNull(),
  description: text("description"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const bookings = mysqlTable("bookings", {
  id: int("id").autoincrement().primaryKey(),
  bookingId: varchar("booking_id", { length: 20 }).notNull().unique(),
  routeId: varchar("route_id", { length: 20 }).notNull(),
  routeName: varchar("route_name", { length: 255 }),
  name: varchar("name", { length: 255 }).notNull(),
  phone: varchar("phone", { length: 50 }).notNull(),
  date: varchar("date", { length: 50 }),
  pax: int("pax").notNull().default(1),
  comment: text("comment"),
  total: int("total"),
  status: varchar("status", { length: 20 }).notNull().default("new"),
  whatsappUrl: text("whatsapp_url"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const providers = mysqlTable("providers", {
  id: int("id").autoincrement().primaryKey(),
  login: varchar("login", { length: 100 }).notNull().unique(),
  passwordHash: varchar("password_hash", { length: 255 }).notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  company: varchar("company", { length: 255 }),
  phone: varchar("phone", { length: 50 }),
  email: varchar("email", { length: 255 }),
  role: varchar("role", { length: 20 }).notNull().default("provider"),
  isActive: int("is_active").notNull().default(1),
  lastLoginAt: timestamp("last_login_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const analytics = mysqlTable("analytics", {
  id: int("id").autoincrement().primaryKey(),
  metric: varchar("metric", { length: 100 }).notNull(),
  category: varchar("category", { length: 50 }),
  label: varchar("label", { length: 100 }),
  value: int("value").notNull().default(0),
  valueFloat: float("value_float"),
  color: varchar("color", { length: 20 }),
  month: varchar("month", { length: 20 }),
  year: int("year"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
